name: Update Stock Price (NVDA)

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours
  workflow_dispatch:       # Allow manual trigger

permissions:
  contents: write  # ✅ Needed to push code

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git for commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch NVDA stock price from Alpha Vantage
        env:
          API_KEY: ${{ secrets.ALPHAVANTAGE_KEY }}
        run: |
          mkdir -p data
          curl -s "https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=NVDA&apikey=$API_KEY" \
          -H "User-Agent: Mozilla/5.0" \
          | jq '{ price: (.["Global Quote"]["05. price"] | tonumber), timestamp: now }' > data/stock.json

      - name: Commit and Push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add data/stock.json
          git commit -m "Update NVDA stock price" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push
